name: wallora
description: "Wallpapers App"
publish_to: 'none'

version: 1.1.7+17

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
   
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
