name: wallora
description: "Wallpapers App"
publish_to: 'none'

version: 1.2.2+21

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1 
  change_app_package_name: ^1.5.0
   
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:

  uses-material-design: true

dependency_overrides:
  characters: ^1.4.1
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  petitparser: ^7.0.0
  test_api: ^0.7.6
  vector_math: ^2.2.0
  vm_service: ^15.0.2
  xml: ^6.6.0
