name: Shorebird OTA Patch

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'shorebird.yaml'

jobs:
  patch_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: shorebirdtech/setup-shorebird@v1
      
      - name: Create Shorebird Android Patch
        run: shorebird patch android --force
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

  patch_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: shorebirdtech/setup-shorebird@v1
      
      - name: Create Shorebird iOS Patch
        run: shorebird patch ios --force
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
