name: Build and Release APK

on:
push:
branches:
- main

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v5

  - name: Setup Java
    uses: actions/setup-java@v5
    with:
      distribution: temurin
      java-version: "21"
      cache: gradle

  - name: Setup Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable

  - name: Install dependencies
    run: flutter pub get

  - name: Get version
    run: |
      VERSION=$(grep '^version:' pubspec.yaml | cut -d':' -f2 | xargs | cut -d'+' -f1)
      echo "VERSION=$VERSION" >> $GITHUB_ENV

  - name: Build APK
    run: flutter build apk --release

  - name: Rename APK
    run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Wallora-${{ env.VERSION }}.apk

  - name: Create Release
    uses: softprops/action-gh-release@v2
    with:
      files: build/app/outputs/flutter-apk/Wallora-${{ env.VERSION }}.apk
      tag_name: v${{ env.VERSION }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
