name: Build and Release APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-24.04-arm
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4' # Recommended version to support Dart SDK 3.10.4+ project requirements
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | cut -d':' -f2 | xargs | cut -d'+' -f1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release --verbose

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Wallora-${{ env.VERSION }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2.5.0
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          files: build/app/outputs/flutter-apk/Wallora-${{ env.VERSION }}.apk
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
